name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run tests
    strategy:
      matrix:
        go: ["1.20"]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go }}
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Run tests
        run: go test ./...
